perlorg/www.pm.org

dns.txt, perl_mongers.xml
(1) Where are you going to host your site's website?
http://gotanda.pm.org/ ( http://gotanda-pm.github.io/ )
(2) Do you want us to host a Mailman mailing list for you?
No thanks.
=> Added Gotanda.pm

perl_mongers.xml
(1) Where are you going to host your site's website?
http://fleet.pm.org ( http://fleet-pm.github.io )
(2) Do you want us to host a Mailman mailing list for you?
Yes please.
=> Add Fleet.pm

perl_mongers.xml
Please change the tsar for stlouis.pm.
=> Change stlous.pm tsar

perl_mongers.xml
Per Jay's suggestion, I am forking and reactivating the Omaha group.  Thanks.
=> Re-activating the Omaha group

perl_mongers.xml
I have moved to Omaha, NE and am closing the inactive Western Montana PM group.
=> No longer a group in Montana

perl_mongers.xml
(1) Where are you going to host your site's website?
http://okinawa.pm.org ( http://okinawapm.github.io ) 
We will hosting our pm.site to GitHub Pages.
(2) Do you want us to host a Mailman mailing list for you?
No thank you.
=> Please add new group from Okinawa, Japan.

perl_mongers.xml
(1) Where are you going to host your site's website?
https://ichesnokov.github.io/ryazan.pm.org/
(2) Do you want us to host a Mailman mailing list for you?
Yes.
=> Add ryazan.pm

perl_mongers.xml
Neil (@neilb) has been arranging the meetings for a while now and we discussed me handing over the group to him. He agreed I should raise this pull request.
=> Hand over thamesvalley.pm to Neil Bowers

perl_mongers.xml
After I stepped down on April, Diego volunteered to be the new contact for Barcelona.pm.
=> Hand over barcelona.pm to Diego Kuperman

bin/xml, perl_mongers.xml
are giving you trouble. For example, on MacOS I now have to run:
PM_ORG_WWW=/Volumes/admin/groups/www perl bin/xml
See #112
=> WebDAV is dead. Long live git!

perl_mongers.xml
Updated the inception date too.
=> Update perl_mongers.xml with new Oslo.pm contact info

perl_mongers.xml
Section 1
1, Please redirect to: http://bcpapm.org
2. IP: 207.38.93.77
3. CNAME: blaircountypa.pm.org
Section 2
1. We do not need a mailing list.
Thanks,
Ben Milliron
=> Adding Blair County Perl Mongers group

perl_mongers.xml
This PR includes up to date details for they Sydney.pm group.
=> Update Sydney PM details

perl_mongers.xml
Updated the contact email address for Shanghai.pm as I will switch to use my @msn.com email address instead in future.
=> Updated Shanghai.pm contact email address for perl_mongers.xml

perl_mongers.xml
Hi, in this PR I add the URL of the meetup for the Barcelona community.
http://www.meetup.com/barcelonapm/
Thank you.
=> Add meetup URL for the Barcelona group

perl_mongers.xml
They boys wanted both listed and Steve at the top
Thanks for your help!!!
Have a great day!
=> Updated Leaders for the Madison Perl Mongers

perl_mongers.xml
Leader changed for the Kansai perl mongers.
And changed the SNS service I am using.
=> Updated tsar for the Kansai perl mongers

perl_mongers.xml
1) https://www.meetup.com/charlotte-pm/ is our web site.
2) No mailing list necessary.
=> Re-activated/updated Charlotte.pm

perl_mongers.xml
Julian Brown is taking over Houston.pm.
=> Change lead for Houston.pm

perl_mongers.xml
=> Add Fuzhou Fujian China PM.ORG

perl_mongers.xml
per https://github.com/perlorg/www.pm.org/issues/193#issuecomment-2289370246
@sjn is this correct?
=> Oslo update

perl_mongers.xml
=> Remove Google Plus links from perl_mongers.xml

perl_mongers.xml
Re-worked version of #220 
@kfly8 @Code-Hex I think this is right except needing Code-Hex email?
=> Okinawa reactivated
